
CREATE TABLE PROFESSOR (
	ID INT IDENTITY(1,1),
	NOME VARCHAR (20) NOT NULL ,
	DISCIPLINA VARCHAR(20)
)

--DROP TABLE PROFESSOR 

INSERT INTO PROFESSOR (NOME) VALUES ('João')

INSERT INTO PROFESSOR VALUES ('Marcus', 'Poo')

SELECT * FROM PROFESSOR