CREATE  DATABASE AULA3_EXEMPLOJOIN3
GO 
USE AULA3_EXEMPLOJOIN3

--DROP DATABASE AULA3_EXEMPLOJOIN3

CREATE TABLE CANDIDATO(
ID_CANDIDATO INT IDENTITY(1,1) PRIMARY KEY,
NOME VARCHAR(50),
PROFISSAO VARCHAR(50), 
)

CREATE TABLE VAGA(
	ID_VAGA INT IDENTITY(1,1) PRIMARY KEY,
	DESCRI플O VARCHAR(100)
)

CREATE TABLE CANDIDATURA(
	ID_CANDIDATURA INT PRIMARY KEY IDENTITY(1,1), 
	ID_VAGA INT NOT NULL REFERENCES VAGA(ID_VAGA) , 
	ID_CANDIDATO INT NOT NULL REFERENCES CANDIDATO(ID_CANDIDATO),
	DATA_CANDIDATURA DATE,
)



INSERT INTO CANDIDATO (NOME, PROFISSAO) VALUES ('Vitor Lassen', 'Dev .net'), ('Anita', 'Dev angular'), ('fernando', 'dev vb')
INSERT INTO CANDIDATO (NOME, PROFISSAO) VALUES ('Erico', 'Dev .net')

INSERT INTO VAGA (DESCRI플O) VALUES ('Desenvolvedor BackEnd'), ('Desenvolvedor Front End')

INSERT INTO VAGA (DESCRI플O) VALUES ('Devops')

INSERT INTO CANDIDATURA (ID_VAGA, ID_CANDIDATO, DATA_CANDIDATURA) VALUES (1,1,'2023-03-16'),(1,3,'2023-03-16')

INSERT INTO CANDIDATURA (ID_VAGA, ID_CANDIDATO, DATA_CANDIDATURA) VALUES (2,1,'2023-03-16')

--DELETE VAGA WHERE ID_VAGA >2

SELECT * FROM VAGA 

SELECT * FROM CANDIDATURA
SELECT * FROM CANDIDATO

--PEGAR INTERSE플O DE TODAS TABELAS 
SELECT * FROM CANDIDATO 
INNER JOIN CANDIDATURA ON CANDIDATO.ID_CANDIDATO = CANDIDATURA.ID_CANDIDATO
INNER JOIN VAGA ON VAGA.ID_VAGA = CANDIDATURA.ID_VAGA


--pEGAR TODOS OS VALORES DA TABELA A ESQUERDA (PARA ISSO OBRIGATORIAMENTE PRECISA UTILIXAR O LEFT EM TODAS JUN합ES)
SELECT * FROM CANDIDATO 
LEFT JOIN CANDIDATURA ON CANDIDATO.ID_CANDIDATO = CANDIDATURA.ID_CANDIDATO
LEFT  JOIN VAGA ON VAGA.ID_VAGA = CANDIDATURA.ID_VAGA

--PEGAR VALORES DA TABELA A ESQUERDA

SELECT * FROM CANDIDATO 
INNER JOIN CANDIDATURA ON CANDIDATO.ID_CANDIDATO = CANDIDATURA.ID_CANDIDATO
RIGHT  JOIN VAGA ON VAGA.ID_VAGA = CANDIDATURA.ID_VAGA