CREATE DATABASE AULA3_JOIN_ESCOLA
GO 
USE AULA3_JOIN_ESCOLA


CREATE TABLE MATERIAS(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	MATERIA VARCHAR(20)
)


CREATE TABLE ALUNOS (
	ID INT IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR (50)
)

CREATE TABLE TURMAS (
	ID INT IDENTITY(1,1) PRIMARY KEY,
	TURMA VARCHAR(50)
)

CREATE TABLE MATERIAS_X_ALUNOS_X_TURMAS(
	ID_ALUNO INT REFERENCES ALUNOS(ID) NOT NULL ,
	ID_MATERIA INT REFERENCES MATERIAS(ID) NOT NULL,
	ID_TURMA INT REFERENCES TURMAS(ID) NOT NULL
)

ALTER TABLE MATERIAS_X_ALUNOS_X_TURMAS ADD PRIMARY KEY (ID_ALUNO, ID_MATERIA, ID_TURMA )


INSERT INTO MATERIAS (MATERIA) VALUES ('Introdução C#') , ('SQL'), ('ANGULAR')


INSERT INTO ALUNOS (NOME) VALUES ('Ana') 
INSERT INTO ALUNOS (NOME) VALUES ('Lucas')
INSERT INTO ALUNOS (NOME) VALUES ('Anita')
INSERT INTO ALUNOS (NOME) VALUES ('Emanuel')

INSERT INTO TURMAS (TURMA) VALUES ('COQUEIROS'),( 'FLORIPA')
INSERT INTO TURMAS (TURMA) VALUES ('NORTE')

INSERT INTO MATERIAS_X_ALUNOS_X_TURMAS (ID_ALUNO, ID_MATERIA,ID_TURMA) VALUES (1,2,1), (1,1,1)
INSERT INTO MATERIAS_X_ALUNOS_X_TURMAS (ID_ALUNO, ID_MATERIA,ID_TURMA) VALUES (2,1,2), (2,3,2)
INSERT INTO MATERIAS_X_ALUNOS_X_TURMAS (ID_ALUNO, ID_MATERIA,ID_TURMA) VALUES  (3,3,2)

INSERT INTO MATERIAS_X_ALUNOS_X_TURMAS (ID_ALUNO, ID_MATERIA,ID_TURMA) VALUES (2,2,1)

SELECT * FROM ALUNOS
SELECT * FROM MATERIAS
SELECT * FROM TURMAS
SELECT * FROM MATERIAS_X_ALUNOS_X_TURMAS WHERE ID_ALUNO = 2


--INNER JOIN 
SELECT ALUNOS.ID AS 'RA', ALUNOS.NOME, MATERIAS.MATERIA, TURMAS.ID, TURMAS.TURMA 
FROM ALUNOS
INNER JOIN MATERIAS_X_ALUNOS_X_TURMAS ON ALUNOS.ID = MATERIAS_X_ALUNOS_X_TURMAS.ID_ALUNO
INNER JOIN MATERIAS ON MATERIAS.ID = MATERIAS_X_ALUNOS_X_TURMAS.ID_MATERIA
INNER JOIN TURMAS ON TURMAS.ID = MATERIAS_X_ALUNOS_X_TURMAS.ID_MATERIA
WHERE MATERIAS.MATERIA = 'Introdução C#'


--INNER JOIN 
SELECT ALUNOS.*, MATERIAS.*, TURMAS.*
FROM ALUNOS
INNER JOIN MATERIAS_X_ALUNOS_X_TURMAS ON ALUNOS.ID = MATERIAS_X_ALUNOS_X_TURMAS.ID_ALUNO
INNER JOIN MATERIAS ON MATERIAS.ID = MATERIAS_X_ALUNOS_X_TURMAS.ID_MATERIA
INNER JOIN TURMAS ON TURMAS.ID = MATERIAS_X_ALUNOS_X_TURMAS.ID_MATERIA
WHERE MATERIAS.MATERIA = 'Introdução C#'
ORDER BY ALUNOS.NOME ASC


--LEFT JOIN 
SELECT *
FROM ALUNOS
LEFT JOIN MATERIAS_X_ALUNOS_X_TURMAS ON ALUNOS.ID = MATERIAS_X_ALUNOS_X_TURMAS.ID_ALUNO
LEFT JOIN MATERIAS ON MATERIAS.ID = MATERIAS_X_ALUNOS_X_TURMAS.ID_MATERIA
LEFT JOIN TURMAS ON TURMAS.ID = MATERIAS_X_ALUNOS_X_TURMAS.ID_TURMA
ORDER BY ALUNOS.NOME ASC



--RIGHT JOIN 
SELECT *
FROM ALUNOS
INNER JOIN MATERIAS_X_ALUNOS_X_TURMAS ON ALUNOS.ID = MATERIAS_X_ALUNOS_X_TURMAS.ID_ALUNO
INNER JOIN MATERIAS ON MATERIAS.ID = MATERIAS_X_ALUNOS_X_TURMAS.ID_MATERIA
RIGHT JOIN TURMAS ON TURMAS.ID = MATERIAS_X_ALUNOS_X_TURMAS.ID_TURMA
ORDER BY ALUNOS.NOME ASC
