CREATE DATABASE AULA2_NORMALIZACAO
GO 
USE AULA2_NORMALIZACAO
--DROP DATABASE AULA2_NORMALIZACAO
--TABELAO FUNCIONARIO NÃO ESTA NORMALIZADO 
CREATE TABLE FUNCIONARIO_NFN(
	CPF VARCHAR(11) PRIMARY KEY,
	NOME VARCHAR(50),
	CARGO VARCHAR(50),
	NUMERO_AGENCIA INT,
	ENDERECO_AGENCIA VARCHAR(100),
	HORAS_TRABALHADAS INT,
	TELEFONE1 VARCHAR(11),
	TELEFONE2 VARCHAR(11)
)

--PRIMEIRA FORMA NORMAL
CREATE TABLE FUNCIONARIO_FN1(
	CPF VARCHAR(11) PRIMARY KEY,
	NOME VARCHAR(50),
	CARGO VARCHAR(50),
	NUMERO_AGENCIA INT,
	ENDERECO_AGENCIA VARCHAR(100),
	HORAS_TRABALHADAS INT
)

CREATE TABLE TELEFONE_FN1(
CPF VARCHAR(11) REFERENCES FUNCIONARIO_FN1(CPF) NOT NULL ,
TELEFONE VARCHAR(11) NOT NULL 
)

ALTER TABLE TELEFONE_FN1 ADD PRIMARY KEY (CPF, TELEFONE)



--SEGUNDA FORMA NORMAL
CREATE TABLE AGENCIA_FN2(
	NUMERO_AGENCIA INT PRIMARY KEY,
	ENDERECO_AGENCIA VARCHAR(100)
)
CREATE TABLE FUNCIONARIO_FN2(
	CPF VARCHAR(11) PRIMARY KEY,
	NOME VARCHAR(50),
	CARGO VARCHAR(50)
)
CREATE TABLE ALOCACAO_FN2 (
	NUMERO_AGENCIA INT REFERENCES AGENCIA_FN2(NUMERO_AGENCIA)NOT NULL ,
	CPF VARCHAR(11) REFERENCES FUNCIONARIO_FN2(CPF)NOT NULL ,
	HORAS_TRABALHADAS INT
)

ALTER TABLE ALOCACAO_FN2 ADD PRIMARY KEY (NUMERO_AGENCIA, CPF)

CREATE TABLE TELEFONE_FN2(
CPF VARCHAR(11) REFERENCES FUNCIONARIO_FN2(CPF)NOT NULL ,
TELEFONE VARCHAR(11) NOT NULL 
)

ALTER TABLE TELEFONE_FN2 ADD PRIMARY KEY (CPF, TELEFONE)


--TERCEIRA FORMA NORMAL
CREATE TABLE AGENCIA_FN3(
	NUMERO_AGENCIA INT PRIMARY KEY,
	ENDERECO_AGENCIA VARCHAR(100)
)

CREATE TABLE CARGO_FN3(
	ID INT IDENTITY (1,1) PRIMARY KEY, 
	CARGO VARCHAR(50)
)

CREATE TABLE FUNCIONARIO_FN3(
	CPF VARCHAR(11) PRIMARY KEY,
	NOME VARCHAR(50),
	CARGO_ID INT REFERENCES CARGO_FN3(ID)
)

CREATE TABLE ALOCACAO_FN3 (
	NUMERO_AGENCIA INT REFERENCES AGENCIA_FN3(NUMERO_AGENCIA) NOT NULL,
	CPF VARCHAR(11) REFERENCES FUNCIONARIO_FN3(CPF) NOT NULL ,
	HORAS_TRABALHADAS INT
)

ALTER TABLE ALOCACAO_FN3 ADD PRIMARY KEY (NUMERO_AGENCIA, CPF)

CREATE TABLE TELEFONE_FN3(
	CPF VARCHAR(11) REFERENCES FUNCIONARIO_FN3(CPF) NOT NULL ,
	TELEFONE VARCHAR(11) NOT NULL
)

ALTER TABLE TELEFONE_FN3 ADD PRIMARY KEY (CPF, TELEFONE)

