CREATE DATABASE AULA2
GO
USE AULA2

--DROP DATABASE AULA2


--RELACIONAMENTO 1:N - UM PRA MUITOS OU N:1 - MUITOS PRA UM 
CREATE TABLE PAIS(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(50),
	SOBRENOME VARCHAR(100),
	DATA_NASCIMENTO DATE, 
	PROFISSAO VARCHAR(50)
)

CREATE TABLE FILHOS(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(50),
	SOBRENOME VARCHAR(100),
	DATA_NASCIMENTO DATE,
	ID_PAI INT REFERENCES PAIS(ID)
)


INSERT INTO PAIS (NOME, SOBRENOME,PROFISSAO, DATA_NASCIMENTO) 
			VALUES ('João', 'Santos', 'Dev', '1980-10-13')
INSERT INTO PAIS (NOME, SOBRENOME,PROFISSAO, DATA_NASCIMENTO) 
			VALUES ('Ana', 'Santos', 'PO', '1985-05-13')



SELECT * FROM PAIS 

INSERT INTO FILHOS (NOME, SOBRENOME, DATA_NASCIMENTO, ID_PAI ) VALUES 
					('Lucas', 'SANTOS' , '2015-10-5', 1),
					('Luiza', 'SANTOS' , '2016-11-5', 1)

INSERT INTO FILHOS (NOME, SOBRENOME, DATA_NASCIMENTO, ID_PAI ) VALUES 
					('Aline', 'SANTOS' , '2013-10-5', 2)

--cONSULTAR O ID DINAMICAMENTE 
INSERT INTO FILHOS (NOME, SOBRENOME, DATA_NASCIMENTO, ID_PAI ) VALUES 
					('Marcos', 'SANTOS' , '2013-10-5', 
						(SELECT ID FROM PAIS WHERE NOME = 'Ana' ))


SELECT * FROM PAIS 
WHERE ID = 2

SELECT * FROM FILHOS 
WHERE ID_PAI = 2


--EXEMPLO RELACIONAMENTO 1:1 (UTOPICO)
CREATE TABLE ESPOSA(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(50),
	SOBRENOME VARCHAR(100),
)

CREATE TABLE ESPOSO(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(50),
	SOBRENOME VARCHAR(100),
	ID_ESPOSA INT REFERENCES ESPOSA(ID) UNIQUE
)

INSERT INTO ESPOSA(NOME, SOBRENOME ) VALUES 
					('Cintia', 'Luciano' ) 


INSERT INTO ESPOSO (NOME, SOBRENOME,ID_ESPOSA ) VALUES 
					('Marcelo', 'Luciano', 1) 

INSERT INTO ESPOSO (NOME, SOBRENOME,ID_ESPOSA ) VALUES 
					('zE BANANEIRO', 'oURO', 1) 

SELECT * FROM ESPOSA 
SELECT * FROM ESPOSO


--RELACIONAMENTO N:N

CREATE TABLE MATERIAS(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	MATERIA VARCHAR(20)
)


CREATE TABLE ALUNOS (
	ID INT IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR (50)
)

CREATE TABLE MATERIAS_X_ALUNOS(
	ID_ALUNO INT REFERENCES ALUNOS(ID) NOT NULL ,
	ID_MATERIA INT REFERENCES MATERIAS(ID) NOT NULL
)

ALTER TABLE MATERIAS_X_ALUNOS ADD PRIMARY KEY (ID_ALUNO, ID_MATERIA)


INSERT INTO MATERIAS (MATERIA) VALUES ('Introdução C#') , ('SQL'), ('ANGULAR')


INSERT INTO ALUNOS (NOME) VALUES ('Ana') 
INSERT INTO ALUNOS (NOME) VALUES ('Lucas')

INSERT INTO MATERIAS_X_ALUNOS (ID_ALUNO, ID_MATERIA) VALUES (1,2), (1,1)
INSERT INTO MATERIAS_X_ALUNOS (ID_ALUNO, ID_MATERIA) VALUES (2,1), (2,3)

SELECT * FROM ALUNOS
SELECT * FROM MATERIAS
SELECT * FROM MATERIAS_X_ALUNOS WHERE ID_ALUNO = 1