CREATE DATABASE AULA2_2
GO 
USE AULA2_2


CREATE TABLE MATERIAS(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	MATERIA VARCHAR(20)
)


CREATE TABLE ALUNOS (
	ID INT IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR (50)
)

CREATE TABLE TURMAS (
	ID INT IDENTITY(1,1) PRIMARY KEY,
	TURMA VARCHAR(50)
)

CREATE TABLE MATERIAS_X_ALUNOS_X_TURMAS(
	ID_ALUNO INT REFERENCES ALUNOS(ID) NOT NULL ,
	ID_MATERIA INT REFERENCES MATERIAS(ID) NOT NULL,
	ID_TURMA INT REFERENCES TURMAS(ID) NOT NULL
)

ALTER TABLE MATERIAS_X_ALUNOS_X_TURMAS ADD PRIMARY KEY (ID_ALUNO, ID_MATERIA, ID_TURMA )


INSERT INTO MATERIAS (MATERIA) VALUES ('Introdução C#') , ('SQL'), ('ANGULAR')


INSERT INTO ALUNOS (NOME) VALUES ('Ana') 
INSERT INTO ALUNOS (NOME) VALUES ('Lucas')

INSERT INTO TURMAS (TURMA) VALUES ('COQUEIROS'),( 'FLORIPA')

INSERT INTO MATERIAS_X_ALUNOS_X_TURMAS (ID_ALUNO, ID_MATERIA,ID_TURMA) VALUES (1,2,1), (1,1,1)
INSERT INTO MATERIAS_X_ALUNOS_X_TURMAS (ID_ALUNO, ID_MATERIA,ID_TURMA) VALUES (2,1,2), (2,3,2)

INSERT INTO MATERIAS_X_ALUNOS_X_TURMAS (ID_ALUNO, ID_MATERIA,ID_TURMA) VALUES (2,2,1)

SELECT * FROM ALUNOS
SELECT * FROM MATERIAS
SELECT * FROM TURMAS
SELECT * FROM MATERIAS_X_ALUNOS_X_TURMAS WHERE ID_ALUNO = 2